name: Uruchom Analizę Minerviniego

on:
  schedule:
    - cron: '0 6 * * *'  # Uruchamia się codziennie o 6:00 rano UTC
  workflow_dispatch:      # Pozwala na ręczne uruchomienie workflow z interfejsu GitHuba

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ustawienie Pythona
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Uruchom skrypt
        run: |
          python main.py

      - name: Publikacja wyników
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Katalog z plikiem HTML i wykresami
          force_orphan: true
          user_name: GitHub Actions
          user_email: actions@github.com
