name: Uruchom Analizę Minerviniego

on:
  schedule:
    - cron: '0 6 * * *'  # Uruchamia się codziennie o 6:00 rano UTC
  workflow_dispatch:      # Pozwala na ręczne uruchomienie workflow z interfejsu GitHuba

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Umożliwia zapisywanie do repozytorium
    steps:
      - uses: actions/checkout@v3

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Uruchom skrypt
        run: |
          python 1download.py

      - name: Publikacja wyników
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Katalog z plikiem HTML i wykresami
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "Deploy GitHub Pages"

