name: Uruchom Analizę Minerviniego

on:
  schedule:
    - cron: '0 21 * * *'  # Uruchamia się codziennie o 21:00 UTC (zamknięcie NYSE)
  workflow_dispatch:      # Pozwala na ręczne uruchomienie workflow z interfejsu GitHuba

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Umożliwia zapisywanie do repozytorium
    steps:
      - uses: actions/checkout@v3

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Uruchom skrypt
        run: |
          python 1download.py

      - name: Dodaj wyniki do repozytorium
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Zaktualizowano wyniki analizy Minerviniego"
          git push origin main
