name: Uruchom Analizę Minerviniego

on:
  schedule:
    # Potencjalne godziny uruchomienia (UTC)
    - cron: '30 12 * * *'  # 14:30 czasu polskiego (CEST)
    - cron: '30 13 * * *'  # 14:30 czasu polskiego (CET)
    - cron: '30 20 * * *'  # 22:30 czasu polskiego (CEST)
    - cron: '30 21 * * *'  # 22:30 czasu polskiego (CET)
  workflow_dispatch:  # Pozwala na ręczne uruchomienie workflow z interfejsu GitHuba

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write   # Pozwala na zapis na GitHub Pages
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sprawdź, czy to właściwy czas
        run: |
          TZ="Europe/Warsaw"  # Ustawienie strefy czasowej na polską
          CURRENT_TIME=$(date +"%H:%M")
          if [[ "$CURRENT_TIME" != "14:30" && "$CURRENT_TIME" != "22:30" ]]; then
            echo "To nie jest właściwy czas. Zakończono."
            exit 0
          fi

      - name: Uruchom skrypt
        run: |
          python 1download.py

      - name: Commituj i pushuj zmiany, jeśli są
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Zaktualizowano wyniki analizy Minerviniego"
            git push origin main
          else
            echo "Brak zmian do commitowania"
          fi

      - name: Deploy na GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Katalog z plikiem HTML
