name: Deploy static content to main

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v4

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .nojekyll file
        run: echo > .nojekyll

      - name: Uruchom skrypt
        run: |
          python 1download.py

      - name: Commituj i pushuj zmiany, jeśli są
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Zaktualizowano wyniki analizy Minerviniego"
            git push origin main
          else
            echo "Brak zmian do commitowania"
